//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action ToolsAction;
    
    private Gtk.ToggleAction RecordImagesAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Image leftimage;
    
    private Gtk.Image rightimage;
    
    private Gtk.HBox hbox2;
    
    private Gtk.CheckButton chkRecord;
    
    private Gtk.CheckButton chkCalibrateLeft;
    
    private Gtk.CheckButton chkCalibrateRight;
    
    private Gtk.CheckButton chkLogging;
    
    private Gtk.CheckButton chkEmbedded;
    
    private Gtk.Button cmdAnimatedGif;
    
    private Gtk.Button cmdTweaks;
    
    private Gtk.Button cmdCalibrateAlignment;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Button cmdSpinLeft;
    
    private Gtk.Button cmdBlank1;
    
    private Gtk.Button cmdSpinRight;
    
    private Gtk.Button cmdBlank2;
    
    private Gtk.Button cmdBlank3;
    
    private Gtk.Button cmd160x128;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Button cmdBackLeft;
    
    private Gtk.Button cmdBack;
    
    private Gtk.Button cmdBackRight;
    
    private Gtk.Button cmdLaserOn;
    
    private Gtk.Button cmdLaserOff;
    
    private Gtk.Button cmd320x256;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Button cmdLeft;
    
    private Gtk.Button cmdStop;
    
    private Gtk.Button cmdRight;
    
    private Gtk.Button cmdAvoid;
    
    private Gtk.Button cmdCrash;
    
    private Gtk.Button cmd640x512;
    
    private Gtk.VBox vbox3;
    
    private Gtk.Label lblReplay;
    
    private Gtk.Entry txtReplay;
    
    private Gtk.Label lblReplayState;
    
    private Gtk.Button cmdReplay;
    
    private Gtk.Button cmdReplayStop;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Button cmdForwardLeft;
    
    private Gtk.Button cmdForward;
    
    private Gtk.Button cmdForwardRight;
    
    private Gtk.Button cmdFast;
    
    private Gtk.Button cmdSlow;
    
    private Gtk.Button cmd1280x1024;
    
    private Gtk.VBox vbox2;
    
    private Gtk.Label lblLogging;
    
    private Gtk.Entry txtLogging;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Button cmdSimpleStereo;
    
    private Gtk.Button cmdDenseStereo;
    
    private Gtk.Button cmdSaveCalibration;
    
    private Gtk.Button cmdSaveCalibrationImage;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("New Action Group");
        this.UIManager.InsertActionGroup(w1, 0);
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.FileAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, "gtk-stop");
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w2.Add(this.ExitAction, null);
        this.ToolsAction = new Gtk.Action("ToolsAction", Mono.Unix.Catalog.GetString("Tools"), null, null);
        this.ToolsAction.ShortLabel = Mono.Unix.Catalog.GetString("Tools");
        w2.Add(this.ToolsAction, null);
        this.RecordImagesAction = new Gtk.ToggleAction("RecordImagesAction", Mono.Unix.Catalog.GetString("Record images"), null, null);
        this.RecordImagesAction.Active = true;
        this.RecordImagesAction.ShortLabel = Mono.Unix.Catalog.GetString("Record images");
        w2.Add(this.RecordImagesAction, null);
        this.UIManager.InsertActionGroup(w2, 1);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.CanFocus = true;
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Surveyor SVS");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='RecordImagesAction' action='RecordImagesAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.leftimage = new Gtk.Image();
        this.leftimage.Name = "leftimage";
        this.hbox1.Add(this.leftimage);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.leftimage]));
        w4.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.rightimage = new Gtk.Image();
        this.rightimage.Name = "rightimage";
        this.hbox1.Add(this.rightimage);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.rightimage]));
        w5.Position = 1;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.chkRecord = new Gtk.CheckButton();
        this.chkRecord.CanFocus = true;
        this.chkRecord.Name = "chkRecord";
        this.chkRecord.Label = Mono.Unix.Catalog.GetString("Record");
        this.chkRecord.DrawIndicator = true;
        this.chkRecord.UseUnderline = true;
        this.hbox2.Add(this.chkRecord);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkRecord]));
        w7.Position = 0;
        // Container child hbox2.Gtk.Box+BoxChild
        this.chkCalibrateLeft = new Gtk.CheckButton();
        this.chkCalibrateLeft.CanFocus = true;
        this.chkCalibrateLeft.Name = "chkCalibrateLeft";
        this.chkCalibrateLeft.Label = Mono.Unix.Catalog.GetString("Calibrate left camera");
        this.chkCalibrateLeft.DrawIndicator = true;
        this.chkCalibrateLeft.UseUnderline = true;
        this.hbox2.Add(this.chkCalibrateLeft);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkCalibrateLeft]));
        w8.Position = 1;
        // Container child hbox2.Gtk.Box+BoxChild
        this.chkCalibrateRight = new Gtk.CheckButton();
        this.chkCalibrateRight.CanFocus = true;
        this.chkCalibrateRight.Name = "chkCalibrateRight";
        this.chkCalibrateRight.Label = Mono.Unix.Catalog.GetString("Calibrate right camera");
        this.chkCalibrateRight.DrawIndicator = true;
        this.chkCalibrateRight.UseUnderline = true;
        this.hbox2.Add(this.chkCalibrateRight);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkCalibrateRight]));
        w9.Position = 2;
        // Container child hbox2.Gtk.Box+BoxChild
        this.chkLogging = new Gtk.CheckButton();
        this.chkLogging.CanFocus = true;
        this.chkLogging.Name = "chkLogging";
        this.chkLogging.Label = Mono.Unix.Catalog.GetString("Logging");
        this.chkLogging.DrawIndicator = true;
        this.chkLogging.UseUnderline = true;
        this.hbox2.Add(this.chkLogging);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkLogging]));
        w10.PackType = ((Gtk.PackType)(1));
        w10.Position = 3;
        // Container child hbox2.Gtk.Box+BoxChild
        this.chkEmbedded = new Gtk.CheckButton();
        this.chkEmbedded.CanFocus = true;
        this.chkEmbedded.Name = "chkEmbedded";
        this.chkEmbedded.Label = Mono.Unix.Catalog.GetString("Embedded");
        this.chkEmbedded.DrawIndicator = true;
        this.chkEmbedded.UseUnderline = true;
        this.hbox2.Add(this.chkEmbedded);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkEmbedded]));
        w11.PackType = ((Gtk.PackType)(1));
        w11.Position = 4;
        // Container child hbox2.Gtk.Box+BoxChild
        this.cmdAnimatedGif = new Gtk.Button();
        this.cmdAnimatedGif.CanFocus = true;
        this.cmdAnimatedGif.Name = "cmdAnimatedGif";
        this.cmdAnimatedGif.UseUnderline = true;
        this.cmdAnimatedGif.Label = Mono.Unix.Catalog.GetString("Save Gif");
        this.hbox2.Add(this.cmdAnimatedGif);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox2[this.cmdAnimatedGif]));
        w12.PackType = ((Gtk.PackType)(1));
        w12.Position = 5;
        w12.Expand = false;
        w12.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.cmdTweaks = new Gtk.Button();
        this.cmdTweaks.CanFocus = true;
        this.cmdTweaks.Name = "cmdTweaks";
        this.cmdTweaks.UseUnderline = true;
        this.cmdTweaks.Label = Mono.Unix.Catalog.GetString("Tweaks");
        this.hbox2.Add(this.cmdTweaks);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox2[this.cmdTweaks]));
        w13.PackType = ((Gtk.PackType)(1));
        w13.Position = 6;
        w13.Expand = false;
        w13.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.cmdCalibrateAlignment = new Gtk.Button();
        this.cmdCalibrateAlignment.CanFocus = true;
        this.cmdCalibrateAlignment.Name = "cmdCalibrateAlignment";
        this.cmdCalibrateAlignment.UseUnderline = true;
        this.cmdCalibrateAlignment.Label = Mono.Unix.Catalog.GetString("Calibrate Alignment");
        this.hbox2.Add(this.cmdCalibrateAlignment);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox2[this.cmdCalibrateAlignment]));
        w14.PackType = ((Gtk.PackType)(1));
        w14.Position = 7;
        w14.Expand = false;
        w14.Fill = false;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w15.Position = 2;
        w15.Expand = false;
        w15.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmdSpinLeft = new Gtk.Button();
        this.cmdSpinLeft.CanFocus = true;
        this.cmdSpinLeft.Name = "cmdSpinLeft";
        this.cmdSpinLeft.UseUnderline = true;
        // Container child cmdSpinLeft.Gtk.Container+ContainerChild
        Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w17 = new Gtk.HBox();
        w17.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w18 = new Gtk.Image();
        w18.Pixbuf = Gdk.Pixbuf.LoadFromResource("ccw.png");
        w17.Add(w18);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w20 = new Gtk.Label();
        w17.Add(w20);
        w16.Add(w17);
        this.cmdSpinLeft.Add(w16);
        this.hbox7.Add(this.cmdSpinLeft);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmdSpinLeft]));
        w24.Position = 0;
        w24.Expand = false;
        w24.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmdBlank1 = new Gtk.Button();
        this.cmdBlank1.CanFocus = true;
        this.cmdBlank1.Name = "cmdBlank1";
        this.cmdBlank1.UseUnderline = true;
        // Container child cmdBlank1.Gtk.Container+ContainerChild
        Gtk.Alignment w25 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w26 = new Gtk.HBox();
        w26.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w27 = new Gtk.Image();
        w27.Pixbuf = Gdk.Pixbuf.LoadFromResource("blank.png");
        w26.Add(w27);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w29 = new Gtk.Label();
        w26.Add(w29);
        w25.Add(w26);
        this.cmdBlank1.Add(w25);
        this.hbox7.Add(this.cmdBlank1);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmdBlank1]));
        w33.Position = 1;
        w33.Expand = false;
        w33.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmdSpinRight = new Gtk.Button();
        this.cmdSpinRight.CanFocus = true;
        this.cmdSpinRight.Name = "cmdSpinRight";
        this.cmdSpinRight.UseUnderline = true;
        // Container child cmdSpinRight.Gtk.Container+ContainerChild
        Gtk.Alignment w34 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w35 = new Gtk.HBox();
        w35.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w36 = new Gtk.Image();
        w36.Pixbuf = Gdk.Pixbuf.LoadFromResource("cw.png");
        w35.Add(w36);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w38 = new Gtk.Label();
        w35.Add(w38);
        w34.Add(w35);
        this.cmdSpinRight.Add(w34);
        this.hbox7.Add(this.cmdSpinRight);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmdSpinRight]));
        w42.Position = 2;
        w42.Expand = false;
        w42.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmdBlank2 = new Gtk.Button();
        this.cmdBlank2.CanFocus = true;
        this.cmdBlank2.Name = "cmdBlank2";
        this.cmdBlank2.UseUnderline = true;
        // Container child cmdBlank2.Gtk.Container+ContainerChild
        Gtk.Alignment w43 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w44 = new Gtk.HBox();
        w44.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w45 = new Gtk.Image();
        w45.Pixbuf = Gdk.Pixbuf.LoadFromResource("blank.png");
        w44.Add(w45);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w47 = new Gtk.Label();
        w44.Add(w47);
        w43.Add(w44);
        this.cmdBlank2.Add(w43);
        this.hbox7.Add(this.cmdBlank2);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmdBlank2]));
        w51.Position = 3;
        w51.Expand = false;
        w51.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmdBlank3 = new Gtk.Button();
        this.cmdBlank3.CanFocus = true;
        this.cmdBlank3.Name = "cmdBlank3";
        this.cmdBlank3.UseUnderline = true;
        // Container child cmdBlank3.Gtk.Container+ContainerChild
        Gtk.Alignment w52 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w53 = new Gtk.HBox();
        w53.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w54 = new Gtk.Image();
        w54.Pixbuf = Gdk.Pixbuf.LoadFromResource("blank.png");
        w53.Add(w54);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w56 = new Gtk.Label();
        w53.Add(w56);
        w52.Add(w53);
        this.cmdBlank3.Add(w52);
        this.hbox7.Add(this.cmdBlank3);
        Gtk.Box.BoxChild w60 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmdBlank3]));
        w60.Position = 4;
        w60.Expand = false;
        w60.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.cmd160x128 = new Gtk.Button();
        this.cmd160x128.CanFocus = true;
        this.cmd160x128.Name = "cmd160x128";
        this.cmd160x128.UseUnderline = true;
        // Container child cmd160x128.Gtk.Container+ContainerChild
        Gtk.Alignment w61 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w62 = new Gtk.HBox();
        w62.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w63 = new Gtk.Image();
        w63.Pixbuf = Gdk.Pixbuf.LoadFromResource("160.png");
        w62.Add(w63);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w65 = new Gtk.Label();
        w62.Add(w65);
        w61.Add(w62);
        this.cmd160x128.Add(w61);
        this.hbox7.Add(this.cmd160x128);
        Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.hbox7[this.cmd160x128]));
        w69.Position = 5;
        w69.Expand = false;
        w69.Fill = false;
        this.vbox1.Add(this.hbox7);
        Gtk.Box.BoxChild w70 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
        w70.PackType = ((Gtk.PackType)(1));
        w70.Position = 3;
        w70.Expand = false;
        w70.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmdBackLeft = new Gtk.Button();
        this.cmdBackLeft.CanFocus = true;
        this.cmdBackLeft.Name = "cmdBackLeft";
        this.cmdBackLeft.UseUnderline = true;
        // Container child cmdBackLeft.Gtk.Container+ContainerChild
        Gtk.Alignment w71 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w72 = new Gtk.HBox();
        w72.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w73 = new Gtk.Image();
        w73.Pixbuf = Gdk.Pixbuf.LoadFromResource("backleft.png");
        w72.Add(w73);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w75 = new Gtk.Label();
        w72.Add(w75);
        w71.Add(w72);
        this.cmdBackLeft.Add(w71);
        this.hbox6.Add(this.cmdBackLeft);
        Gtk.Box.BoxChild w79 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmdBackLeft]));
        w79.Position = 0;
        w79.Expand = false;
        w79.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmdBack = new Gtk.Button();
        this.cmdBack.CanFocus = true;
        this.cmdBack.Name = "cmdBack";
        this.cmdBack.UseUnderline = true;
        // Container child cmdBack.Gtk.Container+ContainerChild
        Gtk.Alignment w80 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w81 = new Gtk.HBox();
        w81.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w82 = new Gtk.Image();
        w82.Pixbuf = Gdk.Pixbuf.LoadFromResource("back.png");
        w81.Add(w82);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w84 = new Gtk.Label();
        w81.Add(w84);
        w80.Add(w81);
        this.cmdBack.Add(w80);
        this.hbox6.Add(this.cmdBack);
        Gtk.Box.BoxChild w88 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmdBack]));
        w88.Position = 1;
        w88.Expand = false;
        w88.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmdBackRight = new Gtk.Button();
        this.cmdBackRight.CanFocus = true;
        this.cmdBackRight.Name = "cmdBackRight";
        this.cmdBackRight.UseUnderline = true;
        // Container child cmdBackRight.Gtk.Container+ContainerChild
        Gtk.Alignment w89 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w90 = new Gtk.HBox();
        w90.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w91 = new Gtk.Image();
        w91.Pixbuf = Gdk.Pixbuf.LoadFromResource("backright.png");
        w90.Add(w91);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w93 = new Gtk.Label();
        w90.Add(w93);
        w89.Add(w90);
        this.cmdBackRight.Add(w89);
        this.hbox6.Add(this.cmdBackRight);
        Gtk.Box.BoxChild w97 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmdBackRight]));
        w97.Position = 2;
        w97.Expand = false;
        w97.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmdLaserOn = new Gtk.Button();
        this.cmdLaserOn.CanFocus = true;
        this.cmdLaserOn.Name = "cmdLaserOn";
        this.cmdLaserOn.UseUnderline = true;
        // Container child cmdLaserOn.Gtk.Container+ContainerChild
        Gtk.Alignment w98 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w99 = new Gtk.HBox();
        w99.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w100 = new Gtk.Image();
        w100.Pixbuf = Gdk.Pixbuf.LoadFromResource("laser.png");
        w99.Add(w100);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w102 = new Gtk.Label();
        w99.Add(w102);
        w98.Add(w99);
        this.cmdLaserOn.Add(w98);
        this.hbox6.Add(this.cmdLaserOn);
        Gtk.Box.BoxChild w106 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmdLaserOn]));
        w106.Position = 3;
        w106.Expand = false;
        w106.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmdLaserOff = new Gtk.Button();
        this.cmdLaserOff.CanFocus = true;
        this.cmdLaserOff.Name = "cmdLaserOff";
        this.cmdLaserOff.UseUnderline = true;
        // Container child cmdLaserOff.Gtk.Container+ContainerChild
        Gtk.Alignment w107 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w108 = new Gtk.HBox();
        w108.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w109 = new Gtk.Image();
        w109.Pixbuf = Gdk.Pixbuf.LoadFromResource("no-laser.png");
        w108.Add(w109);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w111 = new Gtk.Label();
        w108.Add(w111);
        w107.Add(w108);
        this.cmdLaserOff.Add(w107);
        this.hbox6.Add(this.cmdLaserOff);
        Gtk.Box.BoxChild w115 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmdLaserOff]));
        w115.Position = 4;
        w115.Expand = false;
        w115.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.cmd320x256 = new Gtk.Button();
        this.cmd320x256.CanFocus = true;
        this.cmd320x256.Name = "cmd320x256";
        this.cmd320x256.UseUnderline = true;
        // Container child cmd320x256.Gtk.Container+ContainerChild
        Gtk.Alignment w116 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w117 = new Gtk.HBox();
        w117.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w118 = new Gtk.Image();
        w118.Pixbuf = Gdk.Pixbuf.LoadFromResource("320.png");
        w117.Add(w118);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w120 = new Gtk.Label();
        w117.Add(w120);
        w116.Add(w117);
        this.cmd320x256.Add(w116);
        this.hbox6.Add(this.cmd320x256);
        Gtk.Box.BoxChild w124 = ((Gtk.Box.BoxChild)(this.hbox6[this.cmd320x256]));
        w124.Position = 5;
        w124.Expand = false;
        w124.Fill = false;
        this.vbox1.Add(this.hbox6);
        Gtk.Box.BoxChild w125 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
        w125.PackType = ((Gtk.PackType)(1));
        w125.Position = 4;
        w125.Expand = false;
        w125.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdLeft = new Gtk.Button();
        this.cmdLeft.CanFocus = true;
        this.cmdLeft.Name = "cmdLeft";
        this.cmdLeft.UseUnderline = true;
        // Container child cmdLeft.Gtk.Container+ContainerChild
        Gtk.Alignment w126 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w127 = new Gtk.HBox();
        w127.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w128 = new Gtk.Image();
        w128.Pixbuf = Gdk.Pixbuf.LoadFromResource("turnleft.png");
        w127.Add(w128);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w130 = new Gtk.Label();
        w127.Add(w130);
        w126.Add(w127);
        this.cmdLeft.Add(w126);
        this.hbox5.Add(this.cmdLeft);
        Gtk.Box.BoxChild w134 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdLeft]));
        w134.Position = 0;
        w134.Expand = false;
        w134.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdStop = new Gtk.Button();
        this.cmdStop.CanFocus = true;
        this.cmdStop.Name = "cmdStop";
        this.cmdStop.UseUnderline = true;
        // Container child cmdStop.Gtk.Container+ContainerChild
        Gtk.Alignment w135 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w136 = new Gtk.HBox();
        w136.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w137 = new Gtk.Image();
        w137.Pixbuf = Gdk.Pixbuf.LoadFromResource("stop.png");
        w136.Add(w137);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w139 = new Gtk.Label();
        w136.Add(w139);
        w135.Add(w136);
        this.cmdStop.Add(w135);
        this.hbox5.Add(this.cmdStop);
        Gtk.Box.BoxChild w143 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdStop]));
        w143.Position = 1;
        w143.Expand = false;
        w143.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdRight = new Gtk.Button();
        this.cmdRight.CanFocus = true;
        this.cmdRight.Name = "cmdRight";
        this.cmdRight.UseUnderline = true;
        // Container child cmdRight.Gtk.Container+ContainerChild
        Gtk.Alignment w144 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w145 = new Gtk.HBox();
        w145.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w146 = new Gtk.Image();
        w146.Pixbuf = Gdk.Pixbuf.LoadFromResource("turnright.png");
        w145.Add(w146);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w148 = new Gtk.Label();
        w145.Add(w148);
        w144.Add(w145);
        this.cmdRight.Add(w144);
        this.hbox5.Add(this.cmdRight);
        Gtk.Box.BoxChild w152 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdRight]));
        w152.Position = 2;
        w152.Expand = false;
        w152.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdAvoid = new Gtk.Button();
        this.cmdAvoid.CanFocus = true;
        this.cmdAvoid.Name = "cmdAvoid";
        this.cmdAvoid.UseUnderline = true;
        // Container child cmdAvoid.Gtk.Container+ContainerChild
        Gtk.Alignment w153 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w154 = new Gtk.HBox();
        w154.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w155 = new Gtk.Image();
        w155.Pixbuf = Gdk.Pixbuf.LoadFromResource("avoid.png");
        w154.Add(w155);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w157 = new Gtk.Label();
        w154.Add(w157);
        w153.Add(w154);
        this.cmdAvoid.Add(w153);
        this.hbox5.Add(this.cmdAvoid);
        Gtk.Box.BoxChild w161 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdAvoid]));
        w161.Position = 3;
        w161.Expand = false;
        w161.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdCrash = new Gtk.Button();
        this.cmdCrash.CanFocus = true;
        this.cmdCrash.Name = "cmdCrash";
        this.cmdCrash.UseUnderline = true;
        // Container child cmdCrash.Gtk.Container+ContainerChild
        Gtk.Alignment w162 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w163 = new Gtk.HBox();
        w163.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w164 = new Gtk.Image();
        w164.Pixbuf = Gdk.Pixbuf.LoadFromResource("no-avoid.png");
        w163.Add(w164);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w166 = new Gtk.Label();
        w163.Add(w166);
        w162.Add(w163);
        this.cmdCrash.Add(w162);
        this.hbox5.Add(this.cmdCrash);
        Gtk.Box.BoxChild w170 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdCrash]));
        w170.Position = 4;
        w170.Expand = false;
        w170.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmd640x512 = new Gtk.Button();
        this.cmd640x512.CanFocus = true;
        this.cmd640x512.Name = "cmd640x512";
        this.cmd640x512.UseUnderline = true;
        // Container child cmd640x512.Gtk.Container+ContainerChild
        Gtk.Alignment w171 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w172 = new Gtk.HBox();
        w172.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w173 = new Gtk.Image();
        w173.Pixbuf = Gdk.Pixbuf.LoadFromResource("640.png");
        w172.Add(w173);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w175 = new Gtk.Label();
        w172.Add(w175);
        w171.Add(w172);
        this.cmd640x512.Add(w171);
        this.hbox5.Add(this.cmd640x512);
        Gtk.Box.BoxChild w179 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmd640x512]));
        w179.Position = 5;
        w179.Expand = false;
        w179.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.lblReplay = new Gtk.Label();
        this.lblReplay.Name = "lblReplay";
        this.lblReplay.LabelProp = Mono.Unix.Catalog.GetString("Replay name");
        this.vbox3.Add(this.lblReplay);
        Gtk.Box.BoxChild w180 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblReplay]));
        w180.Position = 0;
        w180.Expand = false;
        w180.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.txtReplay = new Gtk.Entry();
        this.txtReplay.CanFocus = true;
        this.txtReplay.Name = "txtReplay";
        this.txtReplay.IsEditable = true;
        this.txtReplay.InvisibleChar = '●';
        this.vbox3.Add(this.txtReplay);
        Gtk.Box.BoxChild w181 = ((Gtk.Box.BoxChild)(this.vbox3[this.txtReplay]));
        w181.Position = 1;
        w181.Expand = false;
        w181.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.lblReplayState = new Gtk.Label();
        this.lblReplayState.Name = "lblReplayState";
        this.vbox3.Add(this.lblReplayState);
        Gtk.Box.BoxChild w182 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblReplayState]));
        w182.Position = 2;
        w182.Expand = false;
        w182.Fill = false;
        this.hbox5.Add(this.vbox3);
        Gtk.Box.BoxChild w183 = ((Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
        w183.Position = 6;
        w183.Expand = false;
        w183.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdReplay = new Gtk.Button();
        this.cmdReplay.CanFocus = true;
        this.cmdReplay.Name = "cmdReplay";
        this.cmdReplay.UseUnderline = true;
        this.cmdReplay.Label = Mono.Unix.Catalog.GetString("Replay");
        this.hbox5.Add(this.cmdReplay);
        Gtk.Box.BoxChild w184 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdReplay]));
        w184.Position = 7;
        w184.Expand = false;
        w184.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.cmdReplayStop = new Gtk.Button();
        this.cmdReplayStop.CanFocus = true;
        this.cmdReplayStop.Name = "cmdReplayStop";
        this.cmdReplayStop.UseUnderline = true;
        this.cmdReplayStop.Label = Mono.Unix.Catalog.GetString("Stop");
        this.hbox5.Add(this.cmdReplayStop);
        Gtk.Box.BoxChild w185 = ((Gtk.Box.BoxChild)(this.hbox5[this.cmdReplayStop]));
        w185.Position = 8;
        w185.Expand = false;
        w185.Fill = false;
        this.vbox1.Add(this.hbox5);
        Gtk.Box.BoxChild w186 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
        w186.PackType = ((Gtk.PackType)(1));
        w186.Position = 5;
        w186.Expand = false;
        w186.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmdForwardLeft = new Gtk.Button();
        this.cmdForwardLeft.CanFocus = true;
        this.cmdForwardLeft.Name = "cmdForwardLeft";
        this.cmdForwardLeft.UseUnderline = true;
        // Container child cmdForwardLeft.Gtk.Container+ContainerChild
        Gtk.Alignment w187 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w188 = new Gtk.HBox();
        w188.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w189 = new Gtk.Image();
        w189.Pixbuf = Gdk.Pixbuf.LoadFromResource("driftleft.png");
        w188.Add(w189);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w191 = new Gtk.Label();
        w188.Add(w191);
        w187.Add(w188);
        this.cmdForwardLeft.Add(w187);
        this.hbox4.Add(this.cmdForwardLeft);
        Gtk.Box.BoxChild w195 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdForwardLeft]));
        w195.Position = 0;
        w195.Expand = false;
        w195.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmdForward = new Gtk.Button();
        this.cmdForward.CanFocus = true;
        this.cmdForward.Name = "cmdForward";
        this.cmdForward.UseUnderline = true;
        // Container child cmdForward.Gtk.Container+ContainerChild
        Gtk.Alignment w196 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w197 = new Gtk.HBox();
        w197.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w198 = new Gtk.Image();
        w198.Pixbuf = Gdk.Pixbuf.LoadFromResource("forward.png");
        w197.Add(w198);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w200 = new Gtk.Label();
        w197.Add(w200);
        w196.Add(w197);
        this.cmdForward.Add(w196);
        this.hbox4.Add(this.cmdForward);
        Gtk.Box.BoxChild w204 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdForward]));
        w204.Position = 1;
        w204.Expand = false;
        w204.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmdForwardRight = new Gtk.Button();
        this.cmdForwardRight.CanFocus = true;
        this.cmdForwardRight.Name = "cmdForwardRight";
        this.cmdForwardRight.UseUnderline = true;
        // Container child cmdForwardRight.Gtk.Container+ContainerChild
        Gtk.Alignment w205 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w206 = new Gtk.HBox();
        w206.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w207 = new Gtk.Image();
        w207.Pixbuf = Gdk.Pixbuf.LoadFromResource("driftright.png");
        w206.Add(w207);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w209 = new Gtk.Label();
        w206.Add(w209);
        w205.Add(w206);
        this.cmdForwardRight.Add(w205);
        this.hbox4.Add(this.cmdForwardRight);
        Gtk.Box.BoxChild w213 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdForwardRight]));
        w213.Position = 2;
        w213.Expand = false;
        w213.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmdFast = new Gtk.Button();
        this.cmdFast.CanFocus = true;
        this.cmdFast.Name = "cmdFast";
        this.cmdFast.UseUnderline = true;
        // Container child cmdFast.Gtk.Container+ContainerChild
        Gtk.Alignment w214 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w215 = new Gtk.HBox();
        w215.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w216 = new Gtk.Image();
        w216.Pixbuf = Gdk.Pixbuf.LoadFromResource("mot9.png");
        w215.Add(w216);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w218 = new Gtk.Label();
        w215.Add(w218);
        w214.Add(w215);
        this.cmdFast.Add(w214);
        this.hbox4.Add(this.cmdFast);
        Gtk.Box.BoxChild w222 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdFast]));
        w222.Position = 3;
        w222.Expand = false;
        w222.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmdSlow = new Gtk.Button();
        this.cmdSlow.CanFocus = true;
        this.cmdSlow.Name = "cmdSlow";
        this.cmdSlow.UseUnderline = true;
        // Container child cmdSlow.Gtk.Container+ContainerChild
        Gtk.Alignment w223 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w224 = new Gtk.HBox();
        w224.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w225 = new Gtk.Image();
        w225.Pixbuf = Gdk.Pixbuf.LoadFromResource("mot5.png");
        w224.Add(w225);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w227 = new Gtk.Label();
        w224.Add(w227);
        w223.Add(w224);
        this.cmdSlow.Add(w223);
        this.hbox4.Add(this.cmdSlow);
        Gtk.Box.BoxChild w231 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdSlow]));
        w231.Position = 4;
        w231.Expand = false;
        w231.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.cmd1280x1024 = new Gtk.Button();
        this.cmd1280x1024.CanFocus = true;
        this.cmd1280x1024.Name = "cmd1280x1024";
        this.cmd1280x1024.UseUnderline = true;
        // Container child cmd1280x1024.Gtk.Container+ContainerChild
        Gtk.Alignment w232 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w233 = new Gtk.HBox();
        w233.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w234 = new Gtk.Image();
        w234.Pixbuf = Gdk.Pixbuf.LoadFromResource("1280.png");
        w233.Add(w234);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w236 = new Gtk.Label();
        w233.Add(w236);
        w232.Add(w233);
        this.cmd1280x1024.Add(w232);
        this.hbox4.Add(this.cmd1280x1024);
        Gtk.Box.BoxChild w240 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmd1280x1024]));
        w240.Position = 5;
        w240.Expand = false;
        w240.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.lblLogging = new Gtk.Label();
        this.lblLogging.Name = "lblLogging";
        this.lblLogging.LabelProp = Mono.Unix.Catalog.GetString("Log name");
        this.vbox2.Add(this.lblLogging);
        Gtk.Box.BoxChild w241 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblLogging]));
        w241.Position = 0;
        w241.Expand = false;
        w241.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.txtLogging = new Gtk.Entry();
        this.txtLogging.CanFocus = true;
        this.txtLogging.Name = "txtLogging";
        this.txtLogging.IsEditable = true;
        this.txtLogging.InvisibleChar = '●';
        this.txtLogging.Xalign = 0.01F;
        this.vbox2.Add(this.txtLogging);
        Gtk.Box.BoxChild w242 = ((Gtk.Box.BoxChild)(this.vbox2[this.txtLogging]));
        w242.Position = 1;
        w242.Expand = false;
        w242.Fill = false;
        this.hbox4.Add(this.vbox2);
        Gtk.Box.BoxChild w243 = ((Gtk.Box.BoxChild)(this.hbox4[this.vbox2]));
        w243.Position = 6;
        w243.Expand = false;
        w243.Fill = false;
        this.vbox1.Add(this.hbox4);
        Gtk.Box.BoxChild w244 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
        w244.PackType = ((Gtk.PackType)(1));
        w244.Position = 6;
        w244.Expand = false;
        w244.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cmdSimpleStereo = new Gtk.Button();
        this.cmdSimpleStereo.CanFocus = true;
        this.cmdSimpleStereo.Name = "cmdSimpleStereo";
        this.cmdSimpleStereo.UseUnderline = true;
        this.cmdSimpleStereo.Label = Mono.Unix.Catalog.GetString("Simple Stereo");
        this.hbox3.Add(this.cmdSimpleStereo);
        Gtk.Box.BoxChild w245 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmdSimpleStereo]));
        w245.Position = 0;
        w245.Expand = false;
        w245.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cmdDenseStereo = new Gtk.Button();
        this.cmdDenseStereo.CanFocus = true;
        this.cmdDenseStereo.Name = "cmdDenseStereo";
        this.cmdDenseStereo.UseUnderline = true;
        this.cmdDenseStereo.Label = Mono.Unix.Catalog.GetString("Dense Stereo");
        this.hbox3.Add(this.cmdDenseStereo);
        Gtk.Box.BoxChild w246 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmdDenseStereo]));
        w246.Position = 1;
        w246.Expand = false;
        w246.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cmdSaveCalibration = new Gtk.Button();
        this.cmdSaveCalibration.CanFocus = true;
        this.cmdSaveCalibration.Name = "cmdSaveCalibration";
        this.cmdSaveCalibration.UseUnderline = true;
        this.cmdSaveCalibration.Label = Mono.Unix.Catalog.GetString("Save calibration file");
        this.hbox3.Add(this.cmdSaveCalibration);
        Gtk.Box.BoxChild w247 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmdSaveCalibration]));
        w247.Position = 3;
        w247.Expand = false;
        w247.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cmdSaveCalibrationImage = new Gtk.Button();
        this.cmdSaveCalibrationImage.CanFocus = true;
        this.cmdSaveCalibrationImage.Name = "cmdSaveCalibrationImage";
        this.cmdSaveCalibrationImage.UseUnderline = true;
        this.cmdSaveCalibrationImage.Label = Mono.Unix.Catalog.GetString("Save calibration image");
        this.hbox3.Add(this.cmdSaveCalibrationImage);
        Gtk.Box.BoxChild w248 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmdSaveCalibrationImage]));
        w248.Position = 4;
        w248.Expand = false;
        w248.Fill = false;
        this.vbox1.Add(this.hbox3);
        Gtk.Box.BoxChild w249 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
        w249.PackType = ((Gtk.PackType)(1));
        w249.Position = 7;
        w249.Expand = false;
        w249.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 916;
        this.DefaultHeight = 540;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ExitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
        this.RecordImagesAction.Activated += new System.EventHandler(this.OnRecordImagesActionActivated);
        this.chkRecord.Clicked += new System.EventHandler(this.OnChkRecordClicked);
        this.chkCalibrateLeft.Clicked += new System.EventHandler(this.OnChkCalibrateLeftClicked);
        this.chkCalibrateRight.Clicked += new System.EventHandler(this.OnChkCalibrateRightClicked);
        this.cmdCalibrateAlignment.Clicked += new System.EventHandler(this.OnCmdCalibrateAlignmentClicked);
        this.cmdTweaks.Clicked += new System.EventHandler(this.OnCmdTweaksClicked);
        this.cmdAnimatedGif.Clicked += new System.EventHandler(this.OnCmdAnimatedGifClicked);
        this.chkEmbedded.Clicked += new System.EventHandler(this.OnChkEmbeddedClicked);
        this.chkLogging.Clicked += new System.EventHandler(this.OnChkLoggingClicked);
        this.cmdSimpleStereo.Clicked += new System.EventHandler(this.OnCmdSimpleStereoClicked);
        this.cmdDenseStereo.Clicked += new System.EventHandler(this.OnCmdDenseStereoClicked);
        this.cmdSaveCalibration.Clicked += new System.EventHandler(this.OnCmdSaveCalibrationClicked);
        this.cmdSaveCalibrationImage.Clicked += new System.EventHandler(this.OnCmdSaveCalibrationImageClicked);
        this.cmdForwardLeft.Clicked += new System.EventHandler(this.OnCmdForwardLeftClicked);
        this.cmdForward.Clicked += new System.EventHandler(this.OnCmdForwardClicked);
        this.cmdForward.Activated += new System.EventHandler(this.OnCmdForwardActivated);
        this.cmdForwardRight.Clicked += new System.EventHandler(this.OnCmdForwardRightClicked);
        this.cmdFast.Clicked += new System.EventHandler(this.OnCmdFastClicked);
        this.cmdSlow.Clicked += new System.EventHandler(this.OnCmdSlowClicked);
        this.cmdLeft.Clicked += new System.EventHandler(this.OnCmdLeftClicked);
        this.cmdStop.Clicked += new System.EventHandler(this.OnCmdStopClicked);
        this.cmdStop.Activated += new System.EventHandler(this.OnCmdStopActivated);
        this.cmdRight.Clicked += new System.EventHandler(this.OnCmdRightClicked);
        this.cmdAvoid.Clicked += new System.EventHandler(this.OnCmdAvoidClicked);
        this.cmdCrash.Clicked += new System.EventHandler(this.OnCmdCrashClicked);
        this.cmdReplay.Clicked += new System.EventHandler(this.OnCmdReplayClicked);
        this.cmdReplayStop.Clicked += new System.EventHandler(this.OnCmdReplayStopClicked);
        this.cmdBackLeft.Clicked += new System.EventHandler(this.OnCmdBackLeftClicked);
        this.cmdBack.Clicked += new System.EventHandler(this.OnCmdBackClicked);
        this.cmdBack.Activated += new System.EventHandler(this.OnCmdBackActivated);
        this.cmdBackRight.Clicked += new System.EventHandler(this.OnCmdBackRightClicked);
        this.cmdLaserOn.Clicked += new System.EventHandler(this.OnCmdLaserOnClicked);
        this.cmdSpinLeft.Clicked += new System.EventHandler(this.OnCmdSpinLeftClicked);
        this.cmdSpinRight.Clicked += new System.EventHandler(this.OnCmdSpinRightClicked);
    }
}
