// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mapping {
    
    
    public partial class frmSimulation {
        
        private Gtk.Action File;
        
        private Gtk.Action Close;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Button cmdReset;
        
        private Gtk.Button cmdRun;
        
        private Gtk.Button cmdOptimise;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Button cmdStep;
        
        private Gtk.Button cmdStop;
        
        private Gtk.Image imgOccupancyGrid;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mapping.frmSimulation
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("File"), null, null);
            this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w2.Add(this.File, null);
            this.Close = new Gtk.Action("Close", Mono.Unix.Catalog.GetString("Close"), null, null);
            this.Close.ShortLabel = Mono.Unix.Catalog.GetString("Close");
            w2.Add(this.Close, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "mapping.frmSimulation";
            this.Title = Mono.Unix.Catalog.GetString("Simulation");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child mapping.frmSimulation.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Close'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cmdReset = new Gtk.Button();
            this.cmdReset.CanFocus = true;
            this.cmdReset.Name = "cmdReset";
            this.cmdReset.UseUnderline = true;
            this.cmdReset.Label = Mono.Unix.Catalog.GetString("Reset");
            this.vbox3.Add(this.cmdReset);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.cmdReset]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cmdRun = new Gtk.Button();
            this.cmdRun.CanFocus = true;
            this.cmdRun.Name = "cmdRun";
            this.cmdRun.UseUnderline = true;
            this.cmdRun.Label = Mono.Unix.Catalog.GetString("Run");
            this.vbox3.Add(this.cmdRun);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.cmdRun]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cmdOptimise = new Gtk.Button();
            this.cmdOptimise.CanFocus = true;
            this.cmdOptimise.Name = "cmdOptimise";
            this.cmdOptimise.UseUnderline = true;
            this.cmdOptimise.Label = Mono.Unix.Catalog.GetString("Optimise");
            this.vbox3.Add(this.cmdOptimise);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.cmdOptimise]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            this.hbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.cmdStep = new Gtk.Button();
            this.cmdStep.CanFocus = true;
            this.cmdStep.Name = "cmdStep";
            this.cmdStep.UseUnderline = true;
            this.cmdStep.Label = Mono.Unix.Catalog.GetString("Step");
            this.vbox4.Add(this.cmdStep);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox4[this.cmdStep]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.cmdStop = new Gtk.Button();
            this.cmdStop.CanFocus = true;
            this.cmdStop.Name = "cmdStop";
            this.cmdStop.UseUnderline = true;
            this.cmdStop.Label = Mono.Unix.Catalog.GetString("Stop");
            this.vbox4.Add(this.cmdStop);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox4[this.cmdStop]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.hbox2.Add(this.vbox4);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.imgOccupancyGrid = new Gtk.Image();
            this.imgOccupancyGrid.Name = "imgOccupancyGrid";
            this.hbox1.Add(this.imgOccupancyGrid);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[this.imgOccupancyGrid]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 609;
            this.DefaultHeight = 471;
            this.Show();
            this.Close.Activated += new System.EventHandler(this.OnCloseActivated);
        }
    }
}
