/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* bktr source support. */
/* #undef HAVE_BKTR */

/* V4L1 source support. */
#define HAVE_V4L1 1

/* V4L2 source support. */
#define HAVE_V4L2 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "phil@firestorm.cx"

/* Define to the full name of this package. */
#define PACKAGE_NAME "fswebcam"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "fswebcam 20070108"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fswebcam"

/* Define to the version of this package. */
#define PACKAGE_VERSION "20070108"

/* Allow capture of 2^32 frames */
/* #undef USE_32BIT_BUFFER */
